### ISSUE TITLE
Dropdown multiselect styles aren't working

### ISSUE THREAD

**Issue by viwinger** [HealthConnectLink/HCL-FRONTEND#46]
On results page, the services select button should be square like the print button.

**Comment by phillipskevin** [comment]
I figured out why this is not working. Angular2 will add an attribute to a component in order to scope the styles only to that component.

You can see the `_ngcontent-lfe-5` attribute added to each element inside the `<results-page>` here:
![image](https://cloud.githubusercontent.com/assets/5851984/23823506/b2a0aecc-0629-11e7-817e-9f2ff986a270.png)

The same thing is used to modify each selector in the CSS we create:
![image](https://cloud.githubusercontent.com/assets/5851984/23823522/e5cd0bd8-0629-11e7-80ab-a40d95b9f593.png)

That means that this style will not work:
```css
ss-multiselect-dropdown .dropdown .btn {
	border-radius: 0px;
	height: 50px;
	background: deepskyblue;
}
```

because it gets modified to this:
```css
ss-multiselect-dropdown[_ngcontent-kxe-5]   .dropdown[_ngcontent-kxe-5]   .btn[_ngcontent-kxe-5] {
	border-radius: 0px;
	height: 50px;
	background: deepskyblue;
}
```

This doesn't work because the `.dropdown .btn` is not in this template (so it doesn't have the matching attribute), it's actually in the template for the `<ss-multiselect-dropdown>` component.

Anyway, long story short, we need to add `/deep/` before any css selectors that we want to apply to html within child components. You can read more about this here: https://angular.io/docs/ts/latest/guide/component-styles.html#!#special-selectors.
